kubernetesClusterDomain: cluster.local
pm8SCrdJob:
  main:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    env:
      kubeInClusterConfig: "true"
    image:
      repository: ghcr.io/playm8s/crds
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1500m
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 512Mi
  nodeSelector: {}
  podSecurityContext:
    fsGroupChangePolicy: Always
    runAsNonRoot: true
  tolerations: []
  topologySpreadConstraints: []
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
